# Generated by Django 5.1.4 on 2024-12-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('units', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Materials',
        ),
    ]
