# Generated by Django 5.1.4 on 2024-12-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_app', '0002_material_delete_materials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='labour_id',
            new_name='labour_ids',
        ),
    ]
