# Generated by Django 5.1.4 on 2024-12-05 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_app', '0003_rename_labour_id_project_labour_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='labour_ids',
            new_name='labour_id',
        ),
    ]
