# Generated by Django 5.1.4 on 2024-12-12 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_app', '0006_equipment_project_rename_labour_labours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_name', models.CharField(max_length=255)),
                ('profession_name', models.CharField(blank=True, max_length=255)),
                ('allocated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('units', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='labours',
            name='profession',
        ),
        migrations.DeleteModel(
            name='Materials',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_quantity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='labour_ids',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='material_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='material_quantity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='labour',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction_app.profession'),
        ),
        migrations.DeleteModel(
            name='Labours',
        ),
    ]
